def singlePlayerview() :
    print("\n[======= Single Player =======]\n")
    print("■-------- Difficulity --------■")
    print("|                             |")
    print("| 1 ) Easy                    |")
    print("| 2 ) Normal                  |")
    print("| 3 ) Hard                    |")
    print("| 4 ) Master                  |")
    print("|                             |")
    print("|                             |\n")
